config/routes.rb
# require File.join(File.dirname(__FILE__), '..','worker')
require 'resque_worker/worker'
require 'twitter/twitter_app'

Twitty::Application.routes.draw do
  resources :wall_posts
  
  match "/fire_worker", :to => Worker::App
  
  match '/twitter',     :to => TwitterApp
end

app/models/wall_post.rb
class WallPost < ActiveRecord::Base
  
  after_save :tweet_post
  
  def tweet_post
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wall_posts_controller.rb
class WallPostsController < ApplicationController
  # GET /wall_posts
  # GET /wall_posts.xml
  def index
    @wall_posts = WallPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @wall_posts }
    end
  end

  # GET /wall_posts/1
  # GET /wall_posts/1.xml
  def show
    @wall_post = WallPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @wall_post }
    end
  end

  # GET /wall_posts/new
  # GET /wall_posts/new.xml
  def new
    @wall_post = WallPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @wall_post }
    end
  end

  # GET /wall_posts/1/edit
  def edit
    @wall_post = WallPost.find(params[:id])
  end

  # POST /wall_posts
  # POST /wall_posts.xml
  def create
    @wall_post = WallPost.new(params[:wall_post])

    respond_to do |format|
      if @wall_post.save
        format.html { redirect_to(@wall_post, :notice => 'Wall post was successfully created.') }
        format.xml  { render :xml => @wall_post, :status => :created, :location => @wall_post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @wall_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /wall_posts/1
  # PUT /wall_posts/1.xml
  def update
    @wall_post = WallPost.find(params[:id])

    respond_to do |format|
      if @wall_post.update_attributes(params[:wall_post])
        format.html { redirect_to(@wall_post, :notice => 'Wall post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @wall_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /wall_posts/1
  # DELETE /wall_posts/1.xml
  def destroy
    @wall_post = WallPost.find(params[:id])
    @wall_post.destroy

    respond_to do |format|
      format.html { redirect_to(wall_posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wall_posts_helper.rb
module WallPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitty</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wall_posts/_form.html.erb
<%= form_for(@wall_post) do |f| %>
  <% if @wall_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wall_post.errors.count, "error") %> prohibited this wall_post from being saved:</h2>

      <ul>
      <% @wall_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wall_posts/edit.html.erb
<h1>Editing wall_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @wall_post %> |
<%= link_to 'Back', wall_posts_path %>

app/views/wall_posts/index.html.erb
<h1>Listing wall_posts</h1>

<table>
  <tr>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wall_posts.each do |wall_post| %>
  <tr>
    <td><%= wall_post.message %></td>
    <td><%= link_to 'Show', wall_post %></td>
    <td><%= link_to 'Edit', edit_wall_post_path(wall_post) %></td>
    <td><%= link_to 'Destroy', wall_post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wall post', new_wall_post_path %>

app/views/wall_posts/new.html.erb
<h1>New wall_post</h1>

<%= render 'form' %>

<%= link_to 'Back', wall_posts_path %>

app/views/wall_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @wall_post.message %>
</p>


<%= link_to 'Edit', edit_wall_post_path(@wall_post) %> |
<%= link_to 'Back', wall_posts_path %>